Modernizr/modernizr-neue

- README.md
- package.json
> Remove the need to install `gulp` globally

- frontend/styl/header.styl
> make header links full height on homepage

- frontend/js/download/Detect.js
- frontend/js/download/DetectList.js
- frontend/js/download/DownloadOverlay.js
- frontend/js/download/DownloadOverlayOption.js
- frontend/js/download/DownloadUI.js
- frontend/js/download/LeftColumn.js
- frontend/js/download/Metadata.js
- frontend/js/download/MetadataDocs.js
- frontend/js/download/MetadataList.js
- frontend/js/download/MetadataNotes.js
- frontend/js/download/MetadataPolyfills.js
- frontend/js/download/Option.js
- frontend/js/download/SVGToggle.js
- frontend/js/download/SearchHeader.js
- frontend/js/download/index.js
- frontend/styl/header.styl
- frontend/templates/helpers/ternary.js
- frontend/templates/pages/docs.hbs
- frontend/templates/pages/download.hbs
- frontend/templates/pages/news.hbs
- frontend/templates/partials/header.hbs
- gulpfile.js
- package.json
- Made all components use pure render mixin so static components don’t re-render
- Added active state to nav
- Added ternary helper handlebars templates
- Removed aliasify as uglify has dead code removal
> Some updates

- frontend/styl/home.styl
- frontend/templates/index.hbs
- frontend/templates/pages/resources.hbs
- frontend/templates/partials/boxes.hbs
- frontend/templates/partials/header.hbs
- server/routes/dev.js
This is an almost straight copy of the resources page we have now with a tiny cleanup and removal of yepnope references.
This will round out the last bit of this site.
> Add resources section

- frontend/js/download/Detect.js
- frontend/js/download/DownloadUI.js
- frontend/js/download/LeftColumn.js
- frontend/js/download/Option.js
- frontend/js/download/index.js
- frontend/js/download/workers/serviceworker.js
- server/util/modernizrOptions.js
- renamed 'selected' prop to 'checked', since that is what it actually
represents
- removed PureRenderMixin from the Detect object due to it randomly preventing
renders
- update link to serviceworker caching lib
> updates for release

- .gitignore
- frontend/templates/partials/footer.hbs
- gulpfile.js
> srsly fix font-face-loader

- frontend/js/download/SearchHeader.js
> add maxlength arg to search

- frontend/js/download/SearchHeader.js
This should suffice, but I can’t test locally since the build script isn’t working properly (on my Mac).
> Add build tracking on Build button click

- frontend/templates/partials/footer.hbs
Two lines as per Paul’s request/suggestion.
> Footer simplification

- .travis.yml
- package.json
> Fetch automation script via `npm`

- frontend/templates/helpers/copyright.js
- frontend/templates/pages/license.hbs
- gulpfile.js
- server/routes/dev.js
@patrickkettner this matches what we had and will automagically have the right year.
Alternative to #42
> License page

- posts/2015-10-05-modernizr-3-1-0.markdown
> announce v3.1.0

- frontend/styl/header.styl
> explictly set the flex basis for safari

- docs/intro.md
Fixes https://github.com/Modernizr/Modernizr/issues/1654.
Also a few auto-whitespace removals snuck in here.
cc @jakestubbz @patrickkettner
> Add note about classPrefix being used with enableClasses

- README.md
Ref: https://github.com/alrra/modernizr-neue/commit/a486895c5c993341ff7e14e934c3dd4f405fbc53
> README.md: Remove instruction to install gulp

- frontend/styl/builder/toggle.styl
Should fix https://github.com/Modernizr/Modernizr/issues/2321
> Svg icon fix

- .travis.yml
There are some Error in Travis CI config
> Fix Travis `node_js` version to 4.7.0

- docs/intro.md
Replace `user's` with `users`  
Replace two instances of `it's` with `its`  
Replace `effect` with `affect`
> Fix a few typos

- frontend/js/download/MetadataList.js
- frontend/js/download/util.js
Make warning and notes UI on the metadata-sidebar look like the other boxes
> Update metadata-sidebar layout and style

- CNAME
> try to publish at modernizr.com

- docs/intro.md
> Fix small typo
